{"name": "Ввод почты и отправка формы восстановления", "status": "broken", "statusDetails": {"message": "AttributeError: 'RecoveryPage' object has no attribute '_url'", "trace": "self = <tests.test_recovery.TestRecoveryPassword object at 0x0000027E347AE1B0>\nrecovery_page = <pages.recovery_page.RecoveryPage object at 0x0000027E347AFE00>\n\n    @allure.title(\"Ввод почты и отправка формы восстановления\")\n    def test_recover_password_with_email(self, recovery_page):\n>       recovery_page.open()  # открываем страницу восстановления пароля\n\ntests\\test_recovery.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_page.py:45: in open\n    self._url = url if url else self.path()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.recovery_page.RecoveryPage object at 0x0000027E347AFE00>\n\n    def path(self):\n>       return self._url\nE       AttributeError: 'RecoveryPage' object has no attribute '_url'\n\npages\\recovery_page.py:21: AttributeError"}, "start": 1749737433062, "stop": 1749737433062, "uuid": "5f9d1905-16b5-4d30-a5db-15ad7e7bb700", "historyId": "75beaf0e21ab9a79cf29b26887baa2fd", "testCaseId": "75beaf0e21ab9a79cf29b26887baa2fd", "fullName": "tests.test_recovery.TestRecoveryPassword#test_recover_password_with_email", "labels": [{"name": "feature", "value": "Восстановление пароля"}, {"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_recovery"}, {"name": "subSuite", "value": "TestRecoveryPassword"}, {"name": "host", "value": "DESKTOP-05J7DPF"}, {"name": "thread", "value": "22940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_recovery"}]}